import gpiozero
import time
gz = gpiozero
brickdetector = gz.MotionSensor(27)
btm = gz.Servo(26)
top = gz.Servo(17)

brickdetector.wait_for_motion()
print("Starting Main Demo")
#The Full demo
print("Full Demo")
btm.min()
top.min()
print("Box 1")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)
btm.mid()
print("Box 2")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)
btm.max()
print("Box 3")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)

