from gpiozero import Servo
import time

btm = Servo(17)
top = Servo(26)

#The Drop mechanism
print("Demo of Dropping Bricks")
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)

#The Turn-To-Box mechanism
print("Demo of Multiple Boxes")
btm.min()
print("Box 1")
time.sleep(1)
btm.mid()
print("Box 2")
time.sleep(1)
btm.max()
print("Box 3")
time.sleep(1)

#The Full demo
print("Full Demo")
btm.min()
print(btm.min())
print("Box 1")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)
btm.mid()
print("Box 2")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)
btm.max()
print("Box 3")
time.sleep(1)
top.mid()
print("Dropping into Box")
time.sleep(1)
top.min()
print("going back")
time.sleep(1)
